config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index, :show, :create, :new] do
      resources :comments, only: [:new,:index, :show, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'
  validates :text, presence: true, length: { in: 3..100 }

  after_save :update_post_comment_counter

  private

  def update_post_comment_counter
    post.increment!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_like_counter

  private

  def update_post_like_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { in: 3..250 }
  validates :text, presence: true, length: { in: 3..100 }
  validates :comment_counter, :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_user_post_counter

  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  private

  def update_user_post_counter
    author.increment!(:post_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, length: { in: 3..25 }
  validates :photo, presence: true
  validates :bio, presence: true, length: { in: 10..255 }
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(user_id: @post.author.id, id: @post.id), notice: 'Comment added successfully'
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end

  def destroy
    @like = current_user.likes.find(params[:user_id])
    @like.destroy
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    page = params[:page] || 1
    per_page = 10

    @posts = Post.includes(:author)
      .includes(:comments)
      .where(author: params[:user_id])
      .order(created_at: :asc)
      .offset((page.to_i - 1) * per_page)
      .limit(per_page)

    @total_pages = (current_user.posts.count.to_f / per_page).ceil
    @author = @posts.first.author unless @posts.first.nil?
  end

  def show
    @post = Post.find(params[:id])
    @current_user = User.first
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(current_user), notice: 'Post created successfully!'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:posts).all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Add Commenet to post</h1>

      <%= form_with model: @comment, url: user_post_comments_path, local: true do |form| %>
        <div class="form-group">
          <%= form.label :text %>
          <%= form.text_area :text, class: "form-control", placeholder: "Add your comment" %>
        </div>
        <%= form.submit "Add Commment", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" />
  </head>

  <body>
  <div class="container-fluid">
  <%= yield %>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/likes/new.html.erb
<h1> add like</h1>

app/views/posts/index.html.erb
<div class = "container bg-success">
<%= link_to(user_path(@author)) do %> <!-- Use link_to helper method -->
  <button id="back-btn">⬅</button>
<% end %>

<%= render 'shared/user', user: @author %>
  <% @posts.each do |post| %>
    <a href="/users/<%= post.author.id %>/posts/<%= post.id %>" class="text-decoration-none">
      <div class="mb-3">
        <%= render 'shared/post', post: post %>
        <%= render 'shared/comment', comments: post.recent_comments unless post.recent_comments.empty? %>
      </div>
    </a>
  <% end %>
  <nav class="">
  <ul class="pagination justify-content-center align-items-center">
      <% (1..@total_pages).each do |page| %>
          <li class="page-item"><a class="btn bg-white m-1" href="/users/<%= @author.id %>/posts?page=<%= page %>"><%= page %></a></li>
      <% end %>
  </ul>
</nav>

</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="col-md-6">
      <h1 class="text-center mb-4">Create Post</h1>

      <%= form_with model: @post, url: user_posts_path, local: true do |form| %>
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control", placeholder: "Enter Post Title" %>
        </div>

        <div class="form-group">
          <%= form.label :text %>
          <%= form.text_area :text, class: "form-control", placeholder: "Enter Post Text" %>
        </div>

        <%= form.submit "Create Post", class: "btn btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class = "container bg-success">
<a href="<%= user_posts_path() %>">
    <button id="back-btn">⬅</button>
</a>
<h3>Post "#" by <%= @current_user.name %></h3>
    <a href="/users/<%= @post.author.id %>/posts/<%= @post.id %>" class="text-decoration-none">
      <div class="mb-3">
        <%= render 'shared/post', post:@post %>
        <div class= "row p-3 border">
        <%= link_to 'Add a new commment', "/users/#{@current_user.id}/posts/#{@post.id}/comments/new", class: "btn bg-white" %>
        <%= render partial: "shared/like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author.id } %>
        </div>
        <%= render 'shared/comment', comments: @post.comments unless @post.comments.empty? %>
      </div>
    </a>
</div>

app/views/shared/_comment.html.erb
<div class="card bg-success">
  <div class="card-body">
    <% comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
    <% end %>
  </div>
</div>

app/views/shared/_like.html.erb
<%= form_with model: @like, url: user_post_likes_path(author_id: @user, post_id: @post), local: true do |form| %>
    <%= form.submit "Like" %>
  <% end %>

app/views/shared/_post.html.erb
<div class="card bg-success">
  <div class="card-body">
    <h4 class="card-title"><%= post.title %></h4>
    <p class="text-truncate text-justify"><%= post.text %></p>
    <div class="d-flex justify-content-end gap-1 align-items-end">
      <h6 class ="m-0" >Comments: <%= post.comment_counter %>,</h6>
      <h6 class ="m-0" >Likes: <%= post.like_counter %></h6>
    </div>
  </div>
</div>

app/views/shared/_user.html.erb
<div class="row bg-success p-3 text-black">
  <div class="col-sm-3 text-white">
    <img src="<%= user.photo%>"
    class ="rounded" height="90" alt="Not found"/>
  </div>
  <div class="col-sm-9 border row">
    <div class = " col-sm-9"><h3><%= user.name %><h3></div>
    <div class = " col pull-right text-right "><h6 class ="pt-5 pl-4" > Number of posts: <%= user.post_counter%></h6></div>
  </div>
</div>

app/views/users/index.html.erb
<% if @users.empty? %>
<h1> Plase add user at first</h1>
<%end%>
<div class = "container">
<% @users.each do |user|%>
  <a href="/users/<%= user.id %>" class="text-decoration-none">
        <%= render 'shared/user', user: user %>
  </a>
<%end%>
</div>

app/views/users/show.html.erb
<div class = "container bg-success">
 
  <a href="/users" class="text-decoration-none bg-white text-black"> back </a>
  <%= render 'shared/user', user: @user %>
  <div class= "row p-3 border">
    <h3>Bio</h3>
    <p><%= @user.bio %> </p>
  </div>
  
  <div class= "row p-3 border">
  <%= link_to 'Add a new post', "/users/#{@user.id}/posts/new", class: "btn bg-white" %>
  </div>
  <% @user.recent_posts.each do |post| %>
    <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="text-decoration-none">
      <div class="mb-3">
        <%= render 'shared/post', post: post %>
      </div>
    </a>
  <% end %>
  <div class="w-90 mt-5 d-flex justify-content-center align-items-center ">
    <a href="/users/<%= @user.id %>/posts" class="btn bg-white m-1">See all posts</a>
  </div>
</div>